name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ping:
    name: Ping Streamlit App
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP GET request to Argos DataLab
        run: |
          curl -I -s --max-time 30 https://argos-datalab.streamlit.app